<?php

namespace it\icosaedro\utils;

require_once __DIR__ . "/../../../all.php";

/*. require_module 'spl'; require_module 'openssl'; .*/

use RuntimeException;
use ErrorException;
use UnimplementedException;
/*. if_php_ver_7 .*/
use Throwable;
/*. end_if_php_ver .*/

/**
 * Exports the function to generate secure random bytes.
 * @author Umberto Salsi <salsi@icosaedro.it>
 * @copyright Copyright 2018 by icosaedro.it di Umberto Salsi
 * @version $Date: 2018/03/19 10:16:28 $
 */
class SecureRandom {
	
	/**
	 * Returns cryptographically secure random bytes.
	 * @param int $n Number of bytes requested.
	 * @return string Random bytes.
	 * @throws RuntimeException Failed generating cryptographically secure
	 * bytes. Number of generated bytes differs from request.
	 * @throws UnimplementedException Not supported on this system.
	 */
	static function randomBytes($n)
	{
/*. if_php_ver_7 .*/
		if( is_callable("random_bytes") ){
			try {
				$res = random_bytes($n);
			}
			catch(Throwable $e){
				throw new RuntimeException($e->getMessage(), 1, $e);
			}

		} else
/*. end_if_php_ver .*/
		
		if( PHP_OS === "Linux" || file_exists("/dev/urandom") ){
			try {
				$res = file_get_contents("/dev/urandom", FALSE, NULL, 0, $n);
			}
			catch(ErrorException $e){
				throw new RuntimeException($e->getMessage(), 1, $e);
			}
		
		} else if( is_callable("openssl_random_pseudo_bytes") ){
			$res = openssl_random_pseudo_bytes($n);
			if( $res === FALSE )
				throw new RuntimeException("openssl_random_pseudo_bytes() failed");

		} else {
			throw new UnimplementedException("method " . __METHOD__ . " not implemented on this system. Hint: either use PHP >= 7 or enable the openssl module.");
		}
		if( strlen($res) != $n )
			throw new RuntimeException("asked for $n bytes but generated ".strlen($res));
		return $res;
	}
	
}
